behaviors:
  CubeAgent:  # <-- Ensure this is indented with **spaces** (no tabs!)
    trainer_type: ppo
    hyperparameters:
      batch_size: 1024
      buffer_size: 12000
      learning_rate: 3.0e-4
      beta: 0.003
      epsilon: 0.2
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    max_steps: 1000000
    time_horizon: 64
    summary_freq: 5000